"""add_ondelete_strategy_for_slots

Revision ID: 000458aa9b3e
Revises: 5e9dbfdae478
Create Date: 2026-06-07 21:50:16.637257

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "000458aa9b3e"
down_revision: Union[str, Sequence[str], None] = "5e9dbfdae478"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Накат миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("slots_room_id_fkey"), "slots", type_="foreignkey")
    op.create_foreign_key(
        "slots_room_id_fkey", "slots", "rooms", ["room_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("slots_room_id_fkey", "slots", type_="foreignkey")
    op.create_foreign_key(
        op.f("slots_room_id_fkey"), "slots", "rooms", ["room_id"], ["id"]
    )
    # ### end Alembic commands ###
