"""add_description_field_to_rooms_table

Revision ID: 9df13dc8e1d9
Revises: 31f1d9327eb7
Create Date: 2026-06-07 14:54:45.523350

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9df13dc8e1d9"
down_revision: Union[str, Sequence[str], None] = "31f1d9327eb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Накат миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "description")
    # ### end Alembic commands ###
