"""change_create_and_update_at_fields_datetime_by_default

Revision ID: b9468cc1e145
Revises: 9df13dc8e1d9
Create Date: 2026-06-07 19:40:13.427041

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b9468cc1e145"
down_revision: Union[str, Sequence[str], None] = "9df13dc8e1d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Накат миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rooms",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("TIMEZONE('utc', now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "rooms",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("TIMEZONE('utc', now())"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rooms",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rooms",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
