services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: shift-test:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    command:
      [
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]

  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres: {}
